# Generated by Django 4.0.1 on 2022-01-12 22:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Price",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("symbol", models.CharField(db_index=True, max_length=20, verbose_name="Symbol")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("0"), editable=False, max_digits=18, verbose_name="Price"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("modified", models.DateTimeField(auto_now=True, verbose_name="Modified at")),
            ],
            options={
                "db_table": "prices",
            },
        ),
    ]
