repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.1.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: debug-statements
  - repo: https://github.com/psf/black.git
    rev: 21.12b0
    hooks:
      - id: black
        exclude: |
          (?x)(
              ^\.git/|
              ^cache/|
              ^\.cache/|
              ^venv/|
              ^\.venv/|
              ^\.local/|
              ^migrations/
          )
        language_version: python3
        ## Just check, do not write back to files.
        # args: [--check]
        ## Stage 'manual' requires '--hook-stage manual'.
        # stages: [commit]
        stages: [commit]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        stages: [commit]
  - repo: https://github.com/pycqa/pylint
    rev: v2.12.2
    hooks:
      - id: pylint
        stages: [manual]
