---
version: '3.9'

services:
  test:
    build:
      context: .
      dockerfile: ./Dockerfile.test
      args:
        PYTHON_VERSION: "3.8"
        DEBIAN_VERSION: "slim-buster"
        USER_NAME: "user"
        USER_ID: 1000
        GROUP_ID: 1000
        REQUIREMENTS: "requirements.test.txt"
    command: tox -e py310
    entrypoint: ""
    volumes:
      - ./:/code
    env_file:
      - .env
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
